language: php

env:
  matrix:
    - PHPUNIT_VERSION="~3.0"
    - PHPUNIT_VERSION="~4.0"
    - PHPUNIT_VERSION="~5.0"

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - rm -rf composer.lock vendor/
  - composer self-update
  - composer require --dev phpunit/phpunit $PHPUNIT_VERSION

script:
  - vendor/bin/phpunit

sudo: false
